# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package test - main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Checking - Sort the imports
      run: |
        make isort-check
    - name: Checking - Lint with black
      run: |
        make black-check
    - name: Test with pytest
      env:
        TEST_WM_EMAIL: ${{ secrets.TEST_WM_EMAIL }}
        TEST_WM_PASSWORD: ${{ secrets.TEST_WM_PASSWORD }}
      run: |
        make test
    - name: Build
      run: |
        make build
